trigger:
  branches:
    include:
      - main

schedules:
  - cron: "0 * * * *"
    displayName: Hourly run
    branches:
      include:
        - main

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo "Hello World"
  displayName: 'Run Hello World script'
