trigger:
  branches:
    include:
      - main

schedules:
  - cron: "0 * * * *"
    displayName: Hourly run
    branches:
      include:
        - main
    always: true

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: chmod +x ./dba_hsekeeping.ksh
  displayName: 'Set execute permission on housekeeping script'

- script: ./dba_hsekeeping.ksh
  displayName: 'Run housekeeping script'
