trigger:
  branches:
    include:
      - main

schedules:
  - cron: "0 * * * *"
    displayName: Hourly run
    always: true

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: ./dba_hsekeeping.ksh
  displayName: 'Run Hello World script'
